// packages/vue/src/TableGridPicker.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from "vue";
import { COMMAND_PRIORITY_LOW } from "lexical";
import { SE_OPEN_TABLE_COMMAND } from "seditor-core";
import { INSERT_TABLE_COMMAND } from "seditor-plugin-table";
import { useEditor } from "./useEditor";

const MAX_SIZE = 8;
const instance = useEditor();
const state = ref<{ top: number; left: number } | null>(null);
const hover = ref({ rows: 1, cols: 1 });

function close(): void {
  state.value = null;
}

function insert(rows: number, cols: number): void {
  instance.editor.dispatchCommand(INSERT_TABLE_COMMAND, {
    columns: String(cols),
    rows: String(rows),
    includeHeaders: { rows: true, columns: false },
  });
  instance.editor.focus();
  close();
}

function onKey(event: KeyboardEvent): void {
  if (state.value && event.key === "Escape") {
    event.preventDefault();
    close();
  }
}

function onMouseDown(event: MouseEvent): void {
  if (
    state.value &&
    !(event.target as HTMLElement).closest(".se-table-picker")
  ) {
    close();
  }
}

let unregister: (() => void) | undefined;
onMounted(() => {
  unregister = instance.editor.registerCommand(
    SE_OPEN_TABLE_COMMAND,
    () => {
      const domSel = window.getSelection();
      let top = 0;
      let left = 0;
      if (domSel && domSel.rangeCount > 0) {
        const rect = domSel.getRangeAt(0).getBoundingClientRect();
        top = rect.bottom + 6;
        left = rect.left + rect.width / 2;
      }
      state.value = { top, left };
      hover.value = { rows: 1, cols: 1 };
      return true;
    },
    COMMAND_PRIORITY_LOW,
  );
  document.addEventListener("keydown", onKey);
  document.addEventListener("mousedown", onMouseDown);
});

onBeforeUnmount(() => {
  unregister?.();
  document.removeEventListener("keydown", onKey);
  document.removeEventListener("mousedown", onMouseDown);
});
</script>

<template>
  <div
    v-if="state"
    class="se-table-picker"
    :style="{
      top: `${state.top}px`,
      left: `${state.left}px`,
      transform: 'translateX(-50%)',
      '--se-table-picker-cols': MAX_SIZE,
    }"
    role="dialog"
    aria-label="Insert table"
  >
    <div class="se-table-picker-grid">
      <button
        v-for="index in MAX_SIZE * MAX_SIZE"
        :key="index"
        type="button"
        class="se-table-picker-cell"
        :data-active="
          Math.floor((index - 1) / MAX_SIZE) + 1 <= hover.rows &&
          ((index - 1) % MAX_SIZE) + 1 <= hover.cols
            ? 'true'
            : 'false'
        "
        :aria-label="`${Math.floor((index - 1) / MAX_SIZE) + 1} rows by ${((index - 1) % MAX_SIZE) + 1} columns`"
        @mouseenter="
          hover = {
            rows: Math.floor((index - 1) / MAX_SIZE) + 1,
            cols: ((index - 1) % MAX_SIZE) + 1,
          }
        "
        @click="
          insert(
            Math.floor((index - 1) / MAX_SIZE) + 1,
            ((index - 1) % MAX_SIZE) + 1,
          )
        "
      />
    </div>
    <div class="se-table-picker-label">{{ hover.rows }} × {{ hover.cols }}</div>
  </div>
</template>

// packages/react/src/TableGridPicker.tsx
import { useCallback, useEffect, useState } from "react";
import { COMMAND_PRIORITY_LOW } from "lexical";
import { SE_OPEN_TABLE_COMMAND } from "seditor-core";
import { INSERT_TABLE_COMMAND } from "seditor-plugin-table";
import { useEditor } from "./Editor";

const MAX_SIZE = 8;

interface PickerState {
  top: number;
  left: number;
}

export function TableGridPicker() {
  const instance = useEditor();
  const [state, setState] = useState<PickerState | null>(null);
  const [hover, setHover] = useState<{ rows: number; cols: number }>({
    rows: 1,
    cols: 1,
  });

  useEffect(() => {
    const unregister = instance.editor.registerCommand(
      SE_OPEN_TABLE_COMMAND,
      () => {
        const domSel = window.getSelection();
        let top = 0;
        let left = 0;
        if (domSel && domSel.rangeCount > 0) {
          const rect = domSel.getRangeAt(0).getBoundingClientRect();
          top = rect.bottom + 6;
          left = rect.left + rect.width / 2;
        }
        setState({ top, left });
        setHover({ rows: 1, cols: 1 });
        return true;
      },
      COMMAND_PRIORITY_LOW,
    );
    return unregister;
  }, [instance]);

  const close = useCallback(() => setState(null), []);

  const insert = useCallback(
    (rows: number, cols: number) => {
      instance.editor.dispatchCommand(INSERT_TABLE_COMMAND, {
        columns: String(cols),
        rows: String(rows),
        includeHeaders: { rows: true, columns: false },
      });
      instance.editor.focus();
      close();
    },
    [instance, close],
  );

  useEffect(() => {
    if (!state) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        e.preventDefault();
        close();
      }
    };
    document.addEventListener("keydown", onKey);
    return () => document.removeEventListener("keydown", onKey);
  }, [state, close]);

  useEffect(() => {
    if (!state) return;
    const onMouseDown = (e: MouseEvent) => {
      const target = e.target as HTMLElement;
      if (!target.closest(".se-table-picker")) {
        close();
      }
    };
    document.addEventListener("mousedown", onMouseDown);
    return () => document.removeEventListener("mousedown", onMouseDown);
  }, [state, close]);

  if (!state) return null;

  const cells = [];
  for (let r = 1; r <= MAX_SIZE; r++) {
    for (let c = 1; c <= MAX_SIZE; c++) {
      const active = r <= hover.rows && c <= hover.cols;
      cells.push(
        <button
          key={`${r}-${c}`}
          type="button"
          className="se-table-picker-cell"
          data-active={active ? "true" : "false"}
          onMouseEnter={() => setHover({ rows: r, cols: c })}
          onClick={() => insert(r, c)}
          aria-label={`${r} rows by ${c} columns`}
        />,
      );
    }
  }

  return (
    <div
      className="se-table-picker"
      style={{
        top: state.top,
        left: state.left,
        transform: "translateX(-50%)",
        ["--se-table-picker-cols" as string]: MAX_SIZE,
      }}
      role="dialog"
      aria-label="Insert table"
    >
      <div className="se-table-picker-grid">{cells}</div>
      <div className="se-table-picker-label">
        {hover.rows} × {hover.cols}
      </div>
    </div>
  );
}
